### PR TITLE
Add field to enter an issue number

### LINKED ISSUE #2: Feature Request: Add a field for a (Jira) Issue Number
Feature request:
Add a normal (optional) text field to enter the issue number.
The output of the field should be after the subject in such manner:

```
<type>(<scope>): <subject> [<Issue Number>]
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

### PR DESCRIPTION
**Pull request by janwidmer**
Gives the user the option to enter an issue number, which will be displayed after the short description.

Closes #2

### CODE REVIEW

**Comment by stokito** [comment]
Maybe [<issue no>] should be on start because usually it is there.
Like `MVN-45 perf(config):`

**Comment by alanhe421** [comment]
you can input number in Closes issues

**Comment by janwidmer** [comment]
@stokito it depends.. we are following the standard defined by commitizen (https://github.com/commitizen/cz-cli)..but I can also close the PR as I built the plugin based on this PR for me..

**Comment by darrachequesne** [comment]
Let's close this for now.

It could be fixed by https://github.com/MobileTribe/commit-template-idea-plugin/issues/6 in the future, if someone wants to implement the feature :angel:

**Pull request closed without merging**
